/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.usst;

import java.awt.Image;
import javax.imageio.*;
/**
 *
 * @author asus
 */
public class All_Movie extends javax.swing.JFrame {

    /**
     * Creates new form All_Movie
     */
    public All_Movie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        signin = new javax.swing.JButton();
        login = new javax.swing.JButton();
        back = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        back_scroll = new javax.swing.JPanel();
        allmovie = new javax.swing.JLabel();
        dvd2 = new javax.swing.JLabel();
        dvd3 = new javax.swing.JLabel();
        dvd1 = new javax.swing.JLabel();
        dvdname1 = new javax.swing.JLabel();
        dirname1 = new javax.swing.JLabel();
        dvdname2 = new javax.swing.JLabel();
        dirname2 = new javax.swing.JLabel();
        dvdname3 = new javax.swing.JLabel();
        dirname3 = new javax.swing.JLabel();
        dvd4 = new javax.swing.JLabel();
        dvdname4 = new javax.swing.JLabel();
        dirname4 = new javax.swing.JLabel();
        dvd5 = new javax.swing.JLabel();
        dvdname5 = new javax.swing.JLabel();
        dirname5 = new javax.swing.JLabel();
        dvd6 = new javax.swing.JLabel();
        dvdname6 = new javax.swing.JLabel();
        dirname6 = new javax.swing.JLabel();
        dvd7 = new javax.swing.JLabel();
        dvdname7 = new javax.swing.JLabel();
        dirname7 = new javax.swing.JLabel();
        dvd8 = new javax.swing.JLabel();
        dvdname8 = new javax.swing.JLabel();
        dirname8 = new javax.swing.JLabel();
        dvd9 = new javax.swing.JLabel();
        dvdname9 = new javax.swing.JLabel();
        dirname9 = new javax.swing.JLabel();
        dvd10 = new javax.swing.JLabel();
        dvdname10 = new javax.swing.JLabel();
        dirname10 = new javax.swing.JLabel();
        dvd11 = new javax.swing.JLabel();
        dvdname11 = new javax.swing.JLabel();
        dirname11 = new javax.swing.JLabel();
        dvd12 = new javax.swing.JLabel();
        dvdname12 = new javax.swing.JLabel();
        dirname12 = new javax.swing.JLabel();
        dvd13 = new javax.swing.JLabel();
        dvdname13 = new javax.swing.JLabel();
        dirname13 = new javax.swing.JLabel();
        dvd14 = new javax.swing.JLabel();
        dvdname14 = new javax.swing.JLabel();
        dirname14 = new javax.swing.JLabel();
        dvd15 = new javax.swing.JLabel();
        dvdname15 = new javax.swing.JLabel();
        dirname15 = new javax.swing.JLabel();
        dvd16 = new javax.swing.JLabel();
        dvdname16 = new javax.swing.JLabel();
        dirname16 = new javax.swing.JLabel();
        dvd17 = new javax.swing.JLabel();
        dvdname17 = new javax.swing.JLabel();
        dirname17 = new javax.swing.JLabel();
        dvd18 = new javax.swing.JLabel();
        dvdname18 = new javax.swing.JLabel();
        dirname18 = new javax.swing.JLabel();
        dvd19 = new javax.swing.JLabel();
        dvdname19 = new javax.swing.JLabel();
        dirname19 = new javax.swing.JLabel();
        dvd20 = new javax.swing.JLabel();
        dvdname20 = new javax.swing.JLabel();
        dirname20 = new javax.swing.JLabel();
        allcount = new javax.swing.JLabel();
        dvdnull = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("在线DVD租赁系统");
        setBounds(new java.awt.Rectangle(275, 125, 0, 0));

        background.setBackground(new java.awt.Color(255, 255, 255));

        banner.setBackground(new java.awt.Color(102, 102, 102));
        banner.setPreferredSize(new java.awt.Dimension(186, 60));

        signin.setBackground(new java.awt.Color(102, 102, 102));
        signin.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setText("注册");
        signin.setBorder(null);
        signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(102, 102, 102));
        login.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("登录");
        login.setBorder(null);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(102, 102, 102));
        back.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("返回");
        back.setBorder(null);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        userName.setVisible(false);
        userName.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("你好，UserName");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName))
                .addGap(19, 19, 19))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        back_scroll.setBackground(new java.awt.Color(255, 255, 255));

        allmovie.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        allmovie.setText("全部影片");
        try{
            Image img= ImageIO.read(this.getClass().getResource("/img/logoD.png"));
            this.setIconImage(img);
        }catch(Exception e){

        }

        dvd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname1.setText("影片名称");

        dirname1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname1.setForeground(new java.awt.Color(153, 153, 153));
        dirname1.setText("导演名字");

        dvdname2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname2.setText("影片名称");

        dirname2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname2.setForeground(new java.awt.Color(153, 153, 153));
        dirname2.setText("导演名字");

        dvdname3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname3.setText("影片名称");

        dirname3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname3.setForeground(new java.awt.Color(153, 153, 153));
        dirname3.setText("导演名字");

        dvd4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname4.setText("影片名称");

        dirname4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname4.setForeground(new java.awt.Color(153, 153, 153));
        dirname4.setText("导演名字");

        dvd5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname5.setText("影片名称");

        dirname5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname5.setForeground(new java.awt.Color(153, 153, 153));
        dirname5.setText("导演名字");

        dvd6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname6.setText("影片名称");

        dirname6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname6.setForeground(new java.awt.Color(153, 153, 153));
        dirname6.setText("导演名字");

        dvd7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname7.setText("影片名称");

        dirname7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname7.setForeground(new java.awt.Color(153, 153, 153));
        dirname7.setText("导演名字");

        dvd8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname8.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname8.setText("影片名称");

        dirname8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname8.setForeground(new java.awt.Color(153, 153, 153));
        dirname8.setText("导演名字");

        dvd9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname9.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname9.setText("影片名称");

        dirname9.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname9.setForeground(new java.awt.Color(153, 153, 153));
        dirname9.setText("导演名字");

        dvd10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname10.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname10.setText("影片名称");

        dirname10.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname10.setForeground(new java.awt.Color(153, 153, 153));
        dirname10.setText("导演名字");

        dvd11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname11.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname11.setText("影片名称");

        dirname11.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname11.setForeground(new java.awt.Color(153, 153, 153));
        dirname11.setText("导演名字");

        dvd12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname12.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname12.setText("影片名称");

        dirname12.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname12.setForeground(new java.awt.Color(153, 153, 153));
        dirname12.setText("导演名字");

        dvd13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname13.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname13.setText("影片名称");

        dirname13.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname13.setForeground(new java.awt.Color(153, 153, 153));
        dirname13.setText("导演名字");

        dvd14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname14.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname14.setText("影片名称");

        dirname14.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname14.setForeground(new java.awt.Color(153, 153, 153));
        dirname14.setText("导演名字");

        dvd15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname15.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname15.setText("影片名称");

        dirname15.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname15.setForeground(new java.awt.Color(153, 153, 153));
        dirname15.setText("导演名字");

        dvd16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname16.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname16.setText("影片名称");

        dirname16.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname16.setForeground(new java.awt.Color(153, 153, 153));
        dirname16.setText("导演名字");

        dvd17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname17.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname17.setText("影片名称");

        dirname17.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname17.setForeground(new java.awt.Color(153, 153, 153));
        dirname17.setText("导演名字");

        dvd18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname18.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname18.setText("影片名称");

        dirname18.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname18.setForeground(new java.awt.Color(153, 153, 153));
        dirname18.setText("导演名字");

        dvd19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname19.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname19.setText("影片名称");

        dirname19.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname19.setForeground(new java.awt.Color(153, 153, 153));
        dirname19.setText("导演名字");

        dvd20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname20.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname20.setText("影片名称");

        dirname20.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname20.setForeground(new java.awt.Color(153, 153, 153));
        dirname20.setText("导演名字");

        allcount.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        allcount.setForeground(new java.awt.Color(153, 153, 153));
        allcount.setText("共20部");

        dvdnull.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        dvdnull.setForeground(new java.awt.Color(153, 153, 153));
        dvdnull.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dvdnull.setText("<html>敬请<br/>期待...</html>");

        javax.swing.GroupLayout back_scrollLayout = new javax.swing.GroupLayout(back_scroll);
        back_scroll.setLayout(back_scrollLayout);
        back_scrollLayout.setHorizontalGroup(
            back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back_scrollLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back_scrollLayout.createSequentialGroup()
                        .addComponent(dvd1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dirname1)
                            .addComponent(dvdname1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(dvd2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dirname2)
                            .addComponent(dvdname2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname6)
                                    .addComponent(dvdname6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname3)
                                    .addComponent(dvdname3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname12)
                                    .addComponent(dvdname12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname9)
                                    .addComponent(dvdname9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname4)
                                            .addComponent(dvdname4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname7)
                                            .addComponent(dvdname7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname10)
                                            .addComponent(dvdname10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname13)
                                            .addComponent(dvdname13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname16)
                                            .addComponent(dvdname16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname5)
                                            .addComponent(dvdname5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname8)
                                            .addComponent(dvdname8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname11)
                                            .addComponent(dvdname11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname14)
                                            .addComponent(dvdname14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(allmovie)
                                .addGap(18, 18, 18)
                                .addComponent(allcount))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname19)
                                    .addComponent(dvdname19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname17)
                                            .addComponent(dvdname17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname20)
                                            .addComponent(dvdname20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(28, 28, 28)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname15)
                                    .addComponent(dvdname15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dvdnull, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dvd18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname18)
                                    .addComponent(dvdname18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        back_scrollLayout.setVerticalGroup(
            back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back_scrollLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allmovie)
                    .addComponent(allcount))
                .addGap(18, 18, 18)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dvd1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname2))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname3))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname1)))))
                .addGap(18, 18, 18)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dvd4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname4))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname5))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname6)))))
                .addGap(18, 18, 18)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dvd8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname7))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname8)))))
                        .addGap(18, 18, 18)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dvd11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname10))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname11))))))
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname9)))
                        .addGap(18, 18, 18)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname12)))))
                .addGap(18, 18, 18)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dvd14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname13))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname14)))))
                        .addGap(18, 18, 18)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dvd16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(dvdname16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname16)))
                                .addGap(18, 18, 18)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dvd19, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dvd20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(back_scrollLayout.createSequentialGroup()
                                                .addComponent(dvdname19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dirname19))
                                            .addGroup(back_scrollLayout.createSequentialGroup()
                                                .addComponent(dvdname20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dirname20))))))
                            .addComponent(dvd17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname17))))
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname15)))
                        .addGap(18, 18, 18)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname18)))
                        .addGap(18, 18, 18)
                        .addComponent(dvdnull, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(back_scroll);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        try{
            Homepage hp = new Homepage();
            this.setVisible(false);
            hp.setVisible(true);
        }catch(Exception e){

        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new All_Movie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allcount;
    private javax.swing.JLabel allmovie;
    private javax.swing.JButton back;
    private javax.swing.JPanel back_scroll;
    private javax.swing.JPanel background;
    private javax.swing.JPanel banner;
    private javax.swing.JLabel dirname1;
    private javax.swing.JLabel dirname10;
    private javax.swing.JLabel dirname11;
    private javax.swing.JLabel dirname12;
    private javax.swing.JLabel dirname13;
    private javax.swing.JLabel dirname14;
    private javax.swing.JLabel dirname15;
    private javax.swing.JLabel dirname16;
    private javax.swing.JLabel dirname17;
    private javax.swing.JLabel dirname18;
    private javax.swing.JLabel dirname19;
    private javax.swing.JLabel dirname2;
    private javax.swing.JLabel dirname20;
    private javax.swing.JLabel dirname3;
    private javax.swing.JLabel dirname4;
    private javax.swing.JLabel dirname5;
    private javax.swing.JLabel dirname6;
    private javax.swing.JLabel dirname7;
    private javax.swing.JLabel dirname8;
    private javax.swing.JLabel dirname9;
    private javax.swing.JLabel dvd1;
    private javax.swing.JLabel dvd10;
    private javax.swing.JLabel dvd11;
    private javax.swing.JLabel dvd12;
    private javax.swing.JLabel dvd13;
    private javax.swing.JLabel dvd14;
    private javax.swing.JLabel dvd15;
    private javax.swing.JLabel dvd16;
    private javax.swing.JLabel dvd17;
    private javax.swing.JLabel dvd18;
    private javax.swing.JLabel dvd19;
    private javax.swing.JLabel dvd2;
    private javax.swing.JLabel dvd20;
    private javax.swing.JLabel dvd3;
    private javax.swing.JLabel dvd4;
    private javax.swing.JLabel dvd5;
    private javax.swing.JLabel dvd6;
    private javax.swing.JLabel dvd7;
    private javax.swing.JLabel dvd8;
    private javax.swing.JLabel dvd9;
    private javax.swing.JLabel dvdname1;
    private javax.swing.JLabel dvdname10;
    private javax.swing.JLabel dvdname11;
    private javax.swing.JLabel dvdname12;
    private javax.swing.JLabel dvdname13;
    private javax.swing.JLabel dvdname14;
    private javax.swing.JLabel dvdname15;
    private javax.swing.JLabel dvdname16;
    private javax.swing.JLabel dvdname17;
    private javax.swing.JLabel dvdname18;
    private javax.swing.JLabel dvdname19;
    private javax.swing.JLabel dvdname2;
    private javax.swing.JLabel dvdname20;
    private javax.swing.JLabel dvdname3;
    private javax.swing.JLabel dvdname4;
    private javax.swing.JLabel dvdname5;
    private javax.swing.JLabel dvdname6;
    private javax.swing.JLabel dvdname7;
    private javax.swing.JLabel dvdname8;
    private javax.swing.JLabel dvdname9;
    private javax.swing.JLabel dvdnull;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton login;
    private javax.swing.JButton signin;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
