<<<<<<< HEAD
package com.usst.pages;

=======
>>>>>>> origin/dev
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
<<<<<<< HEAD


import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.jar.Attributes.Name;

import javax.imageio.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

import com.usst.db.LogonCheck;

import dvdSockets.Info_Page_new修改;
import dvdSockets.getPicPath;
import dvdSockets.setPicSize;
=======
package cn.edu.usst;

import java.awt.Image;
import javax.imageio.*;
>>>>>>> origin/dev
/**
 *
 * @author asus
 */
public class All_Movie extends javax.swing.JFrame {

    /**
     * Creates new form All_Movie
     */
<<<<<<< HEAD
    private static final int innerWidth = 246;
    private static final int innerHeight = 345;  
	static LogonCheck logonCheck;
	static String [] classicDvd;
	static String [] hotDvd;
    public All_Movie(getPicPath getPicPath ,int width ,int height,String name) {
        initComponents(getPicPath,width,height,name);
=======
    public All_Movie() {
        initComponents();
>>>>>>> origin/dev
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
<<<<<<< HEAD
    private void initComponents(getPicPath getPicPath ,int width ,int height,String name) {
=======
    private void initComponents() {
>>>>>>> origin/dev

        background = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        signin = new javax.swing.JButton();
        login = new javax.swing.JButton();
        back = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        back_scroll = new javax.swing.JPanel();
        allmovie = new javax.swing.JLabel();
        dvd2 = new javax.swing.JLabel();
        dvd3 = new javax.swing.JLabel();
        dvd1 = new javax.swing.JLabel();
        dvdname1 = new javax.swing.JLabel();
        dirname1 = new javax.swing.JLabel();
        dvdname2 = new javax.swing.JLabel();
        dirname2 = new javax.swing.JLabel();
        dvdname3 = new javax.swing.JLabel();
        dirname3 = new javax.swing.JLabel();
        dvd4 = new javax.swing.JLabel();
        dvdname4 = new javax.swing.JLabel();
        dirname4 = new javax.swing.JLabel();
        dvd5 = new javax.swing.JLabel();
        dvdname5 = new javax.swing.JLabel();
        dirname5 = new javax.swing.JLabel();
        dvd6 = new javax.swing.JLabel();
        dvdname6 = new javax.swing.JLabel();
        dirname6 = new javax.swing.JLabel();
        dvd7 = new javax.swing.JLabel();
        dvdname7 = new javax.swing.JLabel();
        dirname7 = new javax.swing.JLabel();
        dvd8 = new javax.swing.JLabel();
        dvdname8 = new javax.swing.JLabel();
        dirname8 = new javax.swing.JLabel();
        dvd9 = new javax.swing.JLabel();
        dvdname9 = new javax.swing.JLabel();
        dirname9 = new javax.swing.JLabel();
        dvd10 = new javax.swing.JLabel();
        dvdname10 = new javax.swing.JLabel();
        dirname10 = new javax.swing.JLabel();
        dvd11 = new javax.swing.JLabel();
        dvdname11 = new javax.swing.JLabel();
        dirname11 = new javax.swing.JLabel();
        dvd12 = new javax.swing.JLabel();
        dvdname12 = new javax.swing.JLabel();
        dirname12 = new javax.swing.JLabel();
        dvd13 = new javax.swing.JLabel();
        dvdname13 = new javax.swing.JLabel();
        dirname13 = new javax.swing.JLabel();
        dvd14 = new javax.swing.JLabel();
        dvdname14 = new javax.swing.JLabel();
        dirname14 = new javax.swing.JLabel();
        dvd15 = new javax.swing.JLabel();
        dvdname15 = new javax.swing.JLabel();
        dirname15 = new javax.swing.JLabel();
        dvd16 = new javax.swing.JLabel();
        dvdname16 = new javax.swing.JLabel();
        dirname16 = new javax.swing.JLabel();
        dvd17 = new javax.swing.JLabel();
        dvdname17 = new javax.swing.JLabel();
        dirname17 = new javax.swing.JLabel();
        dvd18 = new javax.swing.JLabel();
        dvdname18 = new javax.swing.JLabel();
        dirname18 = new javax.swing.JLabel();
        dvd19 = new javax.swing.JLabel();
        dvdname19 = new javax.swing.JLabel();
        dirname19 = new javax.swing.JLabel();
        dvd20 = new javax.swing.JLabel();
        dvdname20 = new javax.swing.JLabel();
        dirname20 = new javax.swing.JLabel();
        allcount = new javax.swing.JLabel();
        dvdnull = new javax.swing.JLabel();
<<<<<<< HEAD
        logonCheck = new LogonCheck();
        classicDvd = new String[10];
    	classicDvd=logonCheck.finClassicDvd();
    	
    	hotDvd = new String[10];
    	hotDvd = logonCheck.findHotDvd();
=======
>>>>>>> origin/dev

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("在线DVD租赁系统");
        setBounds(new java.awt.Rectangle(275, 125, 0, 0));

        background.setBackground(new java.awt.Color(255, 255, 255));

        banner.setBackground(new java.awt.Color(102, 102, 102));
        banner.setPreferredSize(new java.awt.Dimension(186, 60));

        signin.setBackground(new java.awt.Color(102, 102, 102));
        signin.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setText("注册");
        signin.setBorder(null);
        signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(102, 102, 102));
        login.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("登录");
        login.setBorder(null);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(102, 102, 102));
        back.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("返回");
        back.setBorder(null);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        userName.setVisible(false);
        userName.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("你好，UserName");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName))
                .addGap(19, 19, 19))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        back_scroll.setBackground(new java.awt.Color(255, 255, 255));

        allmovie.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        allmovie.setText("全部影片");
        try{
            Image img= ImageIO.read(this.getClass().getResource("/img/logoD.png"));
            this.setIconImage(img);
        }catch(Exception e){

        }

<<<<<<< HEAD
       

        dvdname1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname1.setText(classicDvd[0]);

        dirname1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname1.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo1 = logonCheck.finDvd(classicDvd[0]) ;
        dirname1.setText(dvdInfo1[0]);

        dvdname2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname2.setText(classicDvd[1]);
    

        dirname2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname2.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo2 = logonCheck.finDvd(classicDvd[1]) ;
        dirname2.setText(dvdInfo2[0]);
        
        dvdname3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname3.setText(classicDvd[2]);

        dirname3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname3.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo3 = logonCheck.finDvd(classicDvd[2]) ;
        dirname3.setText(dvdInfo3[0]);
        

        dvdname4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname4.setText(classicDvd[3]);

        dirname4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname4.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo4 = logonCheck.finDvd(classicDvd[3]) ;
        dirname4.setText(dvdInfo4[0]);
       
        dvdname5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname5.setText(classicDvd[4]);

        dirname5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname5.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo5 = logonCheck.finDvd(classicDvd[4]) ;
        dirname5.setText(dvdInfo5[0]);


        dvdname6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname6.setText(classicDvd[5]);

        dirname6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname6.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo6 = logonCheck.finDvd(classicDvd[5]) ;
        dirname6.setText(dvdInfo6[0]);


        dvdname7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname7.setText(classicDvd[6]);

        dirname7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname7.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo7 = logonCheck.finDvd(classicDvd[6]) ;
        dirname7.setText(dvdInfo7[0]);
        
        dvdname8.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname8.setText(classicDvd[7]);

        dirname8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname8.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo8 = logonCheck.finDvd(classicDvd[7]) ;
        dirname8.setText(dvdInfo8[0]);


        dvdname9.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname9.setText(classicDvd[8]);

        dirname9.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname9.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo9 = logonCheck.finDvd(classicDvd[8]) ;
        dirname9.setText(dvdInfo9[0]);


        dvdname10.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname10.setText(classicDvd[9]);

        dirname10.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname10.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo10 = logonCheck.finDvd(classicDvd[9]) ;
        dirname10.setText(dvdInfo10[0]);


        dvdname11.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname11.setText(hotDvd[0]);

        dirname11.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname11.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo11 = logonCheck.finDvd(hotDvd[0]) ;
        dirname11.setText(dvdInfo11[0]);


        dvdname12.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname12.setText(hotDvd[1]);

        dirname12.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname12.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo12 = logonCheck.finDvd(hotDvd[1]) ;
        dirname12.setText(dvdInfo12[0]);


        dvdname13.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname13.setText(hotDvd[2]);

        dirname13.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname13.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo13 = logonCheck.finDvd(hotDvd[2]) ;
        dirname13.setText(dvdInfo13[0]);


        dvdname14.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname14.setText(hotDvd[3]);

        dirname14.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname14.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo14 = logonCheck.finDvd(hotDvd[3]) ;
        dirname14.setText(dvdInfo14[0]);


        dvdname15.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname15.setText(hotDvd[4]);

        dirname15.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname15.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo15 = logonCheck.finDvd(hotDvd[4]) ;
        dirname15.setText(dvdInfo15[0]);

        dvdname16.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname16.setText(hotDvd[5]);

        dirname16.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname16.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo16 = logonCheck.finDvd(hotDvd[5]) ;
        dirname16.setText(dvdInfo16[0]);

        dvdname17.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname17.setText(hotDvd[6]);

        dirname17.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname17.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo17 = logonCheck.finDvd(hotDvd[6]) ;
        dirname17.setText(dvdInfo17[0]);


        dvdname18.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname18.setText(hotDvd[7]);

        dirname18.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname18.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo18 = logonCheck.finDvd(hotDvd[7]) ;
        dirname18.setText(dvdInfo18[0]);


        dvdname19.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname19.setText(hotDvd[8]);

        dirname19.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname19.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo19 = logonCheck.finDvd(hotDvd[8]) ;
        dirname19.setText(dvdInfo19[0]);

        dvdname20.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname20.setText(hotDvd[9]);

        dirname20.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname20.setForeground(new java.awt.Color(153, 153, 153));
        String[] dvdInfo20 = logonCheck.finDvd(hotDvd[9]) ;
        dirname20.setText(dvdInfo20[0]);
        
        dvd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        
        dvd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dvd4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dvd5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dvd6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
       
        
        new setPicSize(dvdname1.getText(), dvd1, getPicPath, width, height);
        new setPicSize(dvdname2.getText(), dvd2, getPicPath, width, height);
        new setPicSize(dvdname3.getText(), dvd3, getPicPath, width, height);
        new setPicSize(dvdname4.getText(), dvd4, getPicPath, width, height);
        new setPicSize(dvdname5.getText(), dvd5, getPicPath, width, height);
        new setPicSize(dvdname6.getText(), dvd6, getPicPath, width, height);
        new setPicSize(dvdname7.getText(), dvd7, getPicPath, width, height);
        new setPicSize(dvdname8.getText(), dvd8, getPicPath, width, height);
        new setPicSize(dvdname9.getText(), dvd9, getPicPath, width, height);
        new setPicSize(dvdname10.getText(), dvd10, getPicPath, width, height);
        new setPicSize(dvdname11.getText(), dvd11, getPicPath, width, height);
        new setPicSize(dvdname12.getText(), dvd12, getPicPath, width, height);
        new setPicSize(dvdname13.getText(), dvd13, getPicPath, width, height);
        new setPicSize(dvdname14.getText(), dvd14, getPicPath, width, height);
        new setPicSize(dvdname15.getText(), dvd15, getPicPath, width, height);
        new setPicSize(dvdname16.getText(), dvd16, getPicPath, width, height);
        new setPicSize(dvdname17.getText(), dvd17, getPicPath, width, height);
        new setPicSize(dvdname18.getText(), dvd18, getPicPath, width, height);
        new setPicSize(dvdname19.getText(), dvd19, getPicPath, width, height);
        new setPicSize(dvdname20.getText(), dvd20, getPicPath, width, height);
          
        dvd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dvd1MouseClicked(evt,name,getPicPath);
            }
        });
        dvd2.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd2MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd3.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd3MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd4.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd4MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd5.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd5MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd6.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd6MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd7.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd7MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd8.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd8MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd9.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd9MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd10.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd10MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd11.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd11MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd12.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd12MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd13.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd13MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd14.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd14MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd15.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd15MouseClicked(evt,name,getPicPath);
        	}
        });
        
        dvd16.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd16MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd17.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd17MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd18.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd18MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd19.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd19MouseClicked(evt,name,getPicPath);
        	}
        });
        dvd20.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		dvd20MouseClicked(evt,name,getPicPath);
        	}
        });
       
=======
        dvd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname1.setText("影片名称");

        dirname1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname1.setForeground(new java.awt.Color(153, 153, 153));
        dirname1.setText("导演名字");

        dvdname2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname2.setText("影片名称");

        dirname2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname2.setForeground(new java.awt.Color(153, 153, 153));
        dirname2.setText("导演名字");

        dvdname3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname3.setText("影片名称");

        dirname3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname3.setForeground(new java.awt.Color(153, 153, 153));
        dirname3.setText("导演名字");

        dvd4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname4.setText("影片名称");

        dirname4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname4.setForeground(new java.awt.Color(153, 153, 153));
        dirname4.setText("导演名字");

        dvd5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname5.setText("影片名称");

        dirname5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname5.setForeground(new java.awt.Color(153, 153, 153));
        dirname5.setText("导演名字");

        dvd6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname6.setText("影片名称");

        dirname6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname6.setForeground(new java.awt.Color(153, 153, 153));
        dirname6.setText("导演名字");

        dvd7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname7.setText("影片名称");

        dirname7.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname7.setForeground(new java.awt.Color(153, 153, 153));
        dirname7.setText("导演名字");

        dvd8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname8.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname8.setText("影片名称");

        dirname8.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname8.setForeground(new java.awt.Color(153, 153, 153));
        dirname8.setText("导演名字");

        dvd9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname9.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname9.setText("影片名称");

        dirname9.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname9.setForeground(new java.awt.Color(153, 153, 153));
        dirname9.setText("导演名字");

        dvd10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname10.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname10.setText("影片名称");

        dirname10.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname10.setForeground(new java.awt.Color(153, 153, 153));
        dirname10.setText("导演名字");

        dvd11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname11.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname11.setText("影片名称");

        dirname11.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname11.setForeground(new java.awt.Color(153, 153, 153));
        dirname11.setText("导演名字");

        dvd12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname12.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname12.setText("影片名称");

        dirname12.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname12.setForeground(new java.awt.Color(153, 153, 153));
        dirname12.setText("导演名字");

        dvd13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname13.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname13.setText("影片名称");

        dirname13.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname13.setForeground(new java.awt.Color(153, 153, 153));
        dirname13.setText("导演名字");

        dvd14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname14.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname14.setText("影片名称");

        dirname14.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname14.setForeground(new java.awt.Color(153, 153, 153));
        dirname14.setText("导演名字");

        dvd15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname15.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname15.setText("影片名称");

        dirname15.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname15.setForeground(new java.awt.Color(153, 153, 153));
        dirname15.setText("导演名字");

        dvd16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname16.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname16.setText("影片名称");

        dirname16.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname16.setForeground(new java.awt.Color(153, 153, 153));
        dirname16.setText("导演名字");

        dvd17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname17.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname17.setText("影片名称");

        dirname17.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname17.setForeground(new java.awt.Color(153, 153, 153));
        dirname17.setText("导演名字");

        dvd18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname18.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname18.setText("影片名称");

        dirname18.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname18.setForeground(new java.awt.Color(153, 153, 153));
        dirname18.setText("导演名字");

        dvd19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname19.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname19.setText("影片名称");

        dirname19.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname19.setForeground(new java.awt.Color(153, 153, 153));
        dirname19.setText("导演名字");

        dvd20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        dvdname20.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dvdname20.setText("影片名称");

        dirname20.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        dirname20.setForeground(new java.awt.Color(153, 153, 153));
        dirname20.setText("导演名字");

>>>>>>> origin/dev
        allcount.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        allcount.setForeground(new java.awt.Color(153, 153, 153));
        allcount.setText("共20部");

        dvdnull.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        dvdnull.setForeground(new java.awt.Color(153, 153, 153));
        dvdnull.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dvdnull.setText("<html>敬请<br/>期待...</html>");

        javax.swing.GroupLayout back_scrollLayout = new javax.swing.GroupLayout(back_scroll);
        back_scroll.setLayout(back_scrollLayout);
        back_scrollLayout.setHorizontalGroup(
            back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back_scrollLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back_scrollLayout.createSequentialGroup()
                        .addComponent(dvd1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dirname1)
                            .addComponent(dvdname1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(dvd2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dirname2)
                            .addComponent(dvdname2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname6)
                                    .addComponent(dvdname6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname3)
                                    .addComponent(dvdname3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname12)
                                    .addComponent(dvdname12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname9)
                                    .addComponent(dvdname9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25))
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname4)
                                            .addComponent(dvdname4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname7)
                                            .addComponent(dvdname7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname10)
                                            .addComponent(dvdname10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname13)
                                            .addComponent(dvdname13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname16)
                                            .addComponent(dvdname16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname5)
                                            .addComponent(dvdname5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname8)
                                            .addComponent(dvdname8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname11)
                                            .addComponent(dvdname11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname14)
                                            .addComponent(dvdname14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(allmovie)
                                .addGap(18, 18, 18)
                                .addComponent(allcount))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname19)
                                    .addComponent(dvdname19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname17)
                                            .addComponent(dvdname17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvd20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dirname20)
                                            .addComponent(dvdname20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(28, 28, 28)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvd15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname15)
                                    .addComponent(dvdname15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dvdnull, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dvd18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirname18)
                                    .addComponent(dvdname18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        back_scrollLayout.setVerticalGroup(
            back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back_scrollLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allmovie)
                    .addComponent(allcount))
                .addGap(18, 18, 18)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dvd1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname2))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname3))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname1)))))
                .addGap(18, 18, 18)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dvd4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname4))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname5))
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addComponent(dvdname6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname6)))))
                .addGap(18, 18, 18)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dvd8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname7))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname8)))))
                        .addGap(18, 18, 18)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dvd11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname10))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname11))))))
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname9)))
                        .addGap(18, 18, 18)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname12)))))
                .addGap(18, 18, 18)
                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dvd14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname13))
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addComponent(dvdname14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname14)))))
                        .addGap(18, 18, 18)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dvd16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(dvdname16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dirname16)))
                                .addGap(18, 18, 18)
                                .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dvd19, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dvd20, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(back_scrollLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(back_scrollLayout.createSequentialGroup()
                                                .addComponent(dvdname19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dirname19))
                                            .addGroup(back_scrollLayout.createSequentialGroup()
                                                .addComponent(dvdname20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dirname20))))))
                            .addComponent(dvd17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname17))))
                    .addGroup(back_scrollLayout.createSequentialGroup()
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname15)))
                        .addGap(18, 18, 18)
                        .addGroup(back_scrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dvd18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(back_scrollLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(dvdname18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dirname18)))
                        .addGap(18, 18, 18)
                        .addComponent(dvdnull, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(back_scroll);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void dvd1MouseClicked(java.awt.event.MouseEvent evt,String name,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname1.getText());
        //System.out.println(dvdInfo[0]);
        Info_Page_new_.setInfoPage(dvdname1.getText(), dvd1, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, "hi");
    }//GEN-LAST:event_dvd1MouseClicked
    private void dvd2MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath){//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname2.getText());
        Info_Page_new_.setInfoPage(dvdname2.getText(), dvd2, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd3MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname3.getText());
        Info_Page_new_.setInfoPage(dvdname3.getText(), dvd3, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd4MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname4.getText());
        Info_Page_new_.setInfoPage(dvdname4.getText(), dvd4, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd5MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname5.getText());
        Info_Page_new_.setInfoPage(dvdname5.getText(), dvd5, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd6MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname6.getText());
        Info_Page_new_.setInfoPage(dvdname6.getText(), dvd6, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd7MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname7.getText());
        Info_Page_new_.setInfoPage(dvdname7.getText(), dvd7, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd8MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname8.getText());
        Info_Page_new_.setInfoPage(dvdname8.getText(), dvd8, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd9MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname9.getText());
        Info_Page_new_.setInfoPage(dvdname9.getText(), dvd9, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd10MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath){//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname10.getText());
        Info_Page_new_.setInfoPage(dvdname10.getText(), dvd10, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd11MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname11.getText());
        Info_Page_new_.setInfoPage(dvdname11.getText(), dvd11, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd12MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath){//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname12.getText());
        Info_Page_new_.setInfoPage(dvdname12.getText(), dvd12, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd13MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname13.getText());
        Info_Page_new_.setInfoPage(dvdname13.getText(), dvd13, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd14MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname14.getText());
        Info_Page_new_.setInfoPage(dvdname14.getText(), dvd14, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd15MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname15.getText());
        Info_Page_new_.setInfoPage(dvdname15.getText(), dvd15, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd16MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname16.getText());
        Info_Page_new_.setInfoPage(dvdname16.getText(), dvd16, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd17MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname17.getText());
        Info_Page_new_.setInfoPage(dvdname17.getText(), dvd17, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd18MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname18.getText());
        Info_Page_new_.setInfoPage(dvdname18.getText(), dvd18, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd19MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname19.getText());
        Info_Page_new_.setInfoPage(dvdname19.getText(), dvd19, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    private void dvd20MouseClicked(java.awt.event.MouseEvent evt,String loginName,getPicPath getPicPath) {//GEN-FIRST:event_dvd1MouseClicked
        // TODO add your handling code here:
        String []dvdInfo = new String[3];
        dvdInfo = logonCheck.finDvd(dvdname20.getText());
        Info_Page_new_.setInfoPage(dvdname20.getText(), dvd20, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_dvd1MouseClicked

    
=======
>>>>>>> origin/dev
    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        try{
<<<<<<< HEAD
            this.setVisible(false);
=======
            Homepage hp = new Homepage();
            this.setVisible(false);
            hp.setVisible(true);
>>>>>>> origin/dev
        }catch(Exception e){

        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
<<<<<<< HEAD
    public static void setAllMovies(getPicPath getPicPath ,int width ,int height,String name){
    	{
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
        	
    		
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new All_Movie(getPicPath,width,height,name).setVisible(true);
                }
            });
        }
=======
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_Movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new All_Movie().setVisible(true);
            }
        });
>>>>>>> origin/dev
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allcount;
    private javax.swing.JLabel allmovie;
    private javax.swing.JButton back;
    private javax.swing.JPanel back_scroll;
    private javax.swing.JPanel background;
    private javax.swing.JPanel banner;
    private javax.swing.JLabel dirname1;
    private javax.swing.JLabel dirname10;
    private javax.swing.JLabel dirname11;
    private javax.swing.JLabel dirname12;
    private javax.swing.JLabel dirname13;
    private javax.swing.JLabel dirname14;
    private javax.swing.JLabel dirname15;
    private javax.swing.JLabel dirname16;
    private javax.swing.JLabel dirname17;
    private javax.swing.JLabel dirname18;
    private javax.swing.JLabel dirname19;
    private javax.swing.JLabel dirname2;
    private javax.swing.JLabel dirname20;
    private javax.swing.JLabel dirname3;
    private javax.swing.JLabel dirname4;
    private javax.swing.JLabel dirname5;
    private javax.swing.JLabel dirname6;
    private javax.swing.JLabel dirname7;
    private javax.swing.JLabel dirname8;
    private javax.swing.JLabel dirname9;
    private javax.swing.JLabel dvd1;
    private javax.swing.JLabel dvd10;
    private javax.swing.JLabel dvd11;
    private javax.swing.JLabel dvd12;
    private javax.swing.JLabel dvd13;
    private javax.swing.JLabel dvd14;
    private javax.swing.JLabel dvd15;
    private javax.swing.JLabel dvd16;
    private javax.swing.JLabel dvd17;
    private javax.swing.JLabel dvd18;
    private javax.swing.JLabel dvd19;
    private javax.swing.JLabel dvd2;
    private javax.swing.JLabel dvd20;
    private javax.swing.JLabel dvd3;
    private javax.swing.JLabel dvd4;
    private javax.swing.JLabel dvd5;
    private javax.swing.JLabel dvd6;
    private javax.swing.JLabel dvd7;
    private javax.swing.JLabel dvd8;
    private javax.swing.JLabel dvd9;
    private javax.swing.JLabel dvdname1;
    private javax.swing.JLabel dvdname10;
    private javax.swing.JLabel dvdname11;
    private javax.swing.JLabel dvdname12;
    private javax.swing.JLabel dvdname13;
    private javax.swing.JLabel dvdname14;
    private javax.swing.JLabel dvdname15;
    private javax.swing.JLabel dvdname16;
    private javax.swing.JLabel dvdname17;
    private javax.swing.JLabel dvdname18;
    private javax.swing.JLabel dvdname19;
    private javax.swing.JLabel dvdname2;
    private javax.swing.JLabel dvdname20;
    private javax.swing.JLabel dvdname3;
    private javax.swing.JLabel dvdname4;
    private javax.swing.JLabel dvdname5;
    private javax.swing.JLabel dvdname6;
    private javax.swing.JLabel dvdname7;
    private javax.swing.JLabel dvdname8;
    private javax.swing.JLabel dvdname9;
    private javax.swing.JLabel dvdnull;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton login;
    private javax.swing.JButton signin;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
