package com.usst.pages;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.UnknownHostException;
import java.sql.SQLException;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import com.usst.db.LogonCheck;

import dvdSockets.DVDClient;
import dvdSockets.Info_Page_new修改;
import dvdSockets.getPicPath;
import dvdSockets.setPicSize;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author asus
 */
public class Homepage_test extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
	static JTextField text1 ;
	static JPasswordField pwdText;
	static String loginName ;
	static JButton login;
	static JButton signin1;
	private static final int width=90;
	private static final int height=130;
	private static final int innerWidth = 200;
	private static final int innerHeight = 280;  
	private static getPicPath getPicPath;
	private static  LogonCheck logonCheck;
	private static String [] classicDVD ;
	private static String [] hotDVD ;
	private static JTextField jTextField11;
    public Homepage_test() throws UnknownHostException, IOException {
		DVDClient dvdClient=new DVDClient();
		dvdClient.recievePic();
		getPicPath = new getPicPath(dvdClient.getPath());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        signin1 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        Panel_Hot = new javax.swing.JPanel();
        hot = new javax.swing.JLabel();
        dvd1 = new javax.swing.JLabel();
        dvd2 = new javax.swing.JLabel();
        dvd3 = new javax.swing.JLabel();
        dvd4 = new javax.swing.JLabel();
        dvdname1 = new javax.swing.JLabel();
        dvdname3 = new javax.swing.JLabel();
        dvdname4 = new javax.swing.JLabel();
        dvdname2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        classical = new javax.swing.JLabel();
        dvd6 = new javax.swing.JLabel();
        dvdname7 = new javax.swing.JLabel();
        dvd5 = new javax.swing.JLabel();
        dvd7 = new javax.swing.JLabel();
        dvdname5 = new javax.swing.JLabel();
        dvdname8 = new javax.swing.JLabel();
        dvd8 = new javax.swing.JLabel();
        dvdname6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        banner.setBackground(new java.awt.Color(102, 102, 102));
        banner.setPreferredSize(new java.awt.Dimension(186, 60));

        signin1.setBackground(new java.awt.Color(102, 102, 102));
        signin1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        signin1.setForeground(new java.awt.Color(255, 255, 255));
        signin1.setText("注册");
        signin1.setBorder(null);
        signin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(102, 102, 102));
        login.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("登录");
        login.setBorder(null);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jTextField11.setBackground(new java.awt.Color(102, 102, 102));
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
/*
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn/edu/usst/search-icon25.png"))); // NOI18N
        search.setBorder(null);
        search.setPreferredSize(new java.awt.Dimension(22, 22));
*/
        title.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("在线DVD租赁系统");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signin1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(signin1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(title)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        Panel_Hot.setBackground(new java.awt.Color(255, 255, 255));

        hot.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        hot.setText("近期热映 >");

       
        

        dvdname1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname1.setText(hotDVD[0]);

        dvdname3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname3.setText(hotDVD[5]);

        dvdname4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname4.setText(hotDVD[8]);

        dvdname2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname2.setText(hotDVD[6]);
        
        dvd1.setText("img");
        dvd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new setPicSize(dvdname1.getText(), dvd1, getPicPath, width, height);
        dvd1.addMouseListener(new MouseListener() {
			String []dvdInfo = new String[3];
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				//System.out.println(loginName);
				dvdInfo = logonCheck.finDvd(dvdname1.getText());
				Info_Page_new修改.setInfoPage(dvdname1.getText(), dvd1, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
				//this.setVisible(false);
			}
		});
        dvd2.setText("img");
        dvd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new setPicSize(dvdname2.getText(), dvd2, getPicPath, width, height);

        dvd3.setText("img");
        dvd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new setPicSize(dvdname3.getText(), dvd3, getPicPath, width, height);

        dvd4.setText("img");
        dvd4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new setPicSize(dvdname4.getText(), dvd4, getPicPath, width, height);
        
        javax.swing.GroupLayout Panel_HotLayout = new javax.swing.GroupLayout(Panel_Hot);
        Panel_Hot.setLayout(Panel_HotLayout);
        Panel_HotLayout.setHorizontalGroup(
            Panel_HotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_HotLayout.createSequentialGroup()
                .addComponent(hot)
                .addGap(18, 18, 18)
                .addGroup(Panel_HotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_HotLayout.createSequentialGroup()
                        .addComponent(dvd1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dvd2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dvd3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dvd4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_HotLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dvdname1)
                        .addGap(52, 52, 52)
                        .addComponent(dvdname2)
                        .addGap(52, 52, 52)
                        .addComponent(dvdname3)
                        .addGap(52, 52, 52)
                        .addComponent(dvdname4)))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        Panel_HotLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dvd1, dvd2, dvd3, dvd4});

        Panel_HotLayout.setVerticalGroup(
            Panel_HotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_HotLayout.createSequentialGroup()
                .addGroup(Panel_HotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dvd4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_HotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dvd1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dvd2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hot)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_HotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dvdname1)
                    .addComponent(dvdname3)
                    .addComponent(dvdname4)
                    .addComponent(dvdname2))
                .addContainerGap())
        );

        Panel_HotLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dvd1, dvd2, dvd3, dvd4});

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        classical.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        classical.setText("重温经典 >");

        dvdname5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname5.setText(classicDVD[7]); 
        
        dvdname6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname6.setText(classicDVD[1]);
        
        dvdname7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname7.setText(classicDVD[2]);
        
        dvdname8.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dvdname8.setText(classicDVD[3]); 
        
        dvd5.setText("img");
        dvd5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new setPicSize(dvdname5.getText(), dvd5, getPicPath, width, height);

        dvd6.setText("img");
        dvd6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new setPicSize(dvdname6.getText(), dvd6, getPicPath, width, height);

        dvd7.setText("img");
        dvd7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new setPicSize(dvdname7.getText(), dvd7, getPicPath, width, height);

       
        dvd8.setText("img");
        dvd8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        new setPicSize(dvdname8.getText(), dvd8, getPicPath, width, height);
       
        jLabel1.setText("全部 >");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(classical)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dvd5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dvd6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dvd7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dvd8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dvdname8)
                        .addGap(52, 52, 52)
                        .addComponent(dvdname7)
                        .addGap(52, 52, 52)
                        .addComponent(dvdname6)
                        .addGap(52, 52, 52)
                        .addComponent(dvdname5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel1))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dvd8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dvd7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dvd5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dvd6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(classical)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dvdname8)
                    .addComponent(dvdname6)
                    .addComponent(dvdname5)
                    .addComponent(dvdname7)
                    .addComponent(jLabel1)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Panel_Hot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Hot, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(300, 150, 605, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // TODO add your handling code here:
    	Homepage_test.setSignPage();
    }//GEN-LAST:event_signinActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    	Homepage_test.setLoginPage();
    }//GEN-LAST:event_loginActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    	String [] dvdInfo = logonCheck.finDvd(jTextField11.getText());
		Info_Page_new修改.setInfoPage(dvdname1.getText(), dvd1, getPicPath, innerWidth, innerHeight, dvdInfo, logonCheck, loginName);
    }//GEN-LAST:event_jTextField1ActionPerformed

    
public static void setSignPage() {
text1 = new JTextField();
	
	//loginName = "hi";
	JFrame frame= new JFrame("sign in ");
	frame.setBounds(500,200,250,300);
	frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    frame.setVisible(true);
    frame.setLayout(null);			   
    //frm.setVisible(false);

    JLabel label6 = new JLabel("注册");
    label6.setBounds(107,40,50,25);
    frame.getContentPane().add(label6);
   
    
    text1.setHorizontalAlignment(JTextField.LEFT);
    text1.setBounds(60,70,120,30);
    frame.getContentPane().add(text1);
    text1.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			System.out.println("login name "+text1.getText()); 
			loginName = text1.getText();
			
		}
	
	});
    
    pwdText= new JPasswordField();
    pwdText.setText("mypassword");
    pwdText.setEchoChar('*');
    pwdText.setBounds(60,107,120,30);
    frame.getContentPane().add(pwdText);
    pwdText.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			String pwString = String.valueOf(pwdText.getPassword());
			System.out.println("login pw "+ pwString);
		}
	});
	  
	    
	    JButton button3 = new JButton();
	    button3.setText("OK");
	    button3.setBounds(140,150,50,25);
	    frame.getContentPane().add(button3);
	    button3.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				String pwString = String.valueOf(pwdText.getPassword());
				
				logonCheck.register(text1.getText(), pwString);
				
				
				Homepage_test.setLoginPageSuccess(true);
			}
		});
    
}



public static void  setLoginPage() {
	/* old login page
	text1 = new JTextField();
	//loginName = "hi";
	JFrame frame= new JFrame("login");
	frame.setBounds(500,200,250,300);
	frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    frame.setVisible(true);
    frame.setLayout(null);			   
    //frm.setVisible(false);

    JLabel label6 = new JLabel("登陆");
    label6.setBounds(107,40,50,25);
    frame.getContentPane().add(label6);
   
    
    text1.setHorizontalAlignment(JTextField.LEFT);
    text1.setBounds(60,70,120,30);
    frame.getContentPane().add(text1);
    text1.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			loginName = text1.getText();
		}
	}); 
  
    
    JPasswordField pwdText= new JPasswordField();
    pwdText.setText("mypassword");
    pwdText.setEchoChar('*');
    pwdText.setBounds(60,107,120,30);
    frame.getContentPane().add(pwdText);
   old login page*/
	text1 = new JTextField();
	
	//loginName = "hi";
	JFrame frame= new JFrame("login");
	frame.setBounds(500,200,250,300);
	frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    frame.setVisible(true);
    frame.setLayout(null);			   
    //frm.setVisible(false);

    JLabel label6 = new JLabel("登陆");
    label6.setBounds(107,40,50,25);
    frame.getContentPane().add(label6);
   
    
    text1.setHorizontalAlignment(JTextField.LEFT);
    text1.setBounds(60,70,120,30);
    frame.getContentPane().add(text1);
    text1.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			System.out.println("login name "+text1.getText()); 
			loginName = text1.getText();
			
		}
	
	});
    
    pwdText= new JPasswordField();
    pwdText.setText("mypassword");
    pwdText.setEchoChar('*');
    pwdText.setBounds(60,107,120,30);
    frame.getContentPane().add(pwdText);
    pwdText.addActionListener(new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			String pwString = String.valueOf(pwdText.getPassword());
			System.out.println("login pw "+ pwString);
		}
	});
	  
	    
	    JButton button3 = new JButton();
	    button3.setText("OK");
	    button3.setBounds(140,150,50,25);
	    frame.getContentPane().add(button3);
	    button3.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				boolean checkLogin = false;
				try {
					String pwString = String.valueOf(pwdText.getPassword());
					checkLogin = logonCheck.loginCheck(text1.getText(),pwString);
				} catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
					System.out.println();
				}
				
				Homepage_test.setLoginPageSuccess(checkLogin);
			}
		});
	
	    
}
//
public  void loginListener() {
	while (true) {
	System.out.println("wait input");
	if (!(loginName.equals("hi")) ) {
	System.out.println("resset");
	resetBanner();
	System.out.println(text1.getText());
	System.out.println(pwdText.getPassword().toString());
	break;
	}

	}
}

public  void  resetBanner() {
	System.out.println(loginName);
	JLabel label5 = new JLabel(loginName);
	this.getContentPane().add(label5);
	label5.setBounds(510,0,100,25);
	label5.setVisible(true);
	login.setVisible(false);
	signin1.setVisible(false);

	}
public static String returnLoginName() {
	return loginName;
	// TODO Auto-generated method stub
	
}
public static void setLoginPageSuccess(boolean loginSuccess){
	if (loginSuccess) {
		JFrame frame= new JFrame("登录信息");
		frame.setBounds(500,200,400,130);
		frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
	    frame.setVisible(true);
	    frame.setLayout(null);
	    
	    JLabel label1 = new JLabel("Login success or sign in sucess！");
	    label1.setBounds(100,30,150,25);
	    frame.getContentPane().add(label1);
	    
	    JButton button1 = new JButton();
	    button1.setText("返回上层");
	    button1.setBounds(250,60,80,25);
	    frame.getContentPane().add(button1);
	    button1.setVisible(true);
	    
	    loginName = text1.getText();
	}
	else {
		JFrame frame= new JFrame("balabala");
		frame.setBounds(500,200,400,130);
		frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
	    frame.setVisible(true);
	    frame.setLayout(null);
	    
	    JLabel label1 = new JLabel("您未登录 or 您的用户名或密码输入错误！");
	    label1.setBounds(100,30,150,25);
	    frame.getContentPane().add(label1);
	    
	    JButton button1 = new JButton();
	    button1.setText("返回上层");
	    button1.setBounds(250,60,80,25);
	    frame.getContentPane().add(button1);
	    button1.setVisible(true);
	}	
}
    /**
     * @param args the command line arguments
     * @throws IOException 
     * @throws UnknownHostException 
     * @throws SQLException 
     */
    public static void main(String args[]) throws UnknownHostException, IOException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	loginName = "hi";
    	logonCheck =new LogonCheck();
    	classicDVD = logonCheck.finClassicDvd();
    	hotDVD = logonCheck.findHotDvd();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
		Homepage_test homepage=new Homepage_test();
		homepage.setVisible(true); 	
		homepage.loginListener();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	
            }
        });
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Hot;
    private javax.swing.JPanel banner;
    private javax.swing.JLabel classical;
    private javax.swing.JLabel dvd1;
    private javax.swing.JLabel dvd2;
    private javax.swing.JLabel dvd3;
    private javax.swing.JLabel dvd4;
    private javax.swing.JLabel dvd5;
    private javax.swing.JLabel dvd6;
    private javax.swing.JLabel dvd7;
    private javax.swing.JLabel dvd8;
    private javax.swing.JLabel dvdname1;
    private javax.swing.JLabel dvdname2;
    private javax.swing.JLabel dvdname3;
    private javax.swing.JLabel dvdname4;
    private javax.swing.JLabel dvdname5;
    private javax.swing.JLabel dvdname6;
    private javax.swing.JLabel dvdname7;
    private javax.swing.JLabel dvdname8;
    private javax.swing.JLabel hot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton login1;
    private javax.swing.JButton search;
    private javax.swing.JButton signin;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
