package com.usst.pages;

import java.io.IOException;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.UIManager;

import com.usst.db.LogonCheck;
import com.usst.favourate.testReadFile;

import dvdSockets.getPicPath;
import dvdSockets.setPicSize;

/**
 *
 * @author asus
 */
public class Info_Page_new_ extends javax.swing.JFrame {
//    static JLabel poster;
    static String lo ; 
    public static JButton login1;
    public static JButton signin1;
    public static JLabel userName1;
    /**
     * Creates new form Info_Page_new
     */
    public Info_Page_new_(){
        
    }
    public Info_Page_new_(String [] dvdInfo,LogonCheck logonCheck,String name,String text1) {
    
    	jPanel1 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        signin1 = new javax.swing.JButton();
        login1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        right = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        director = new javax.swing.JLabel();
        cast = new javax.swing.JLabel();
        name_D = new javax.swing.JLabel();
        name_C = new javax.swing.JLabel();
        introduction = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        intro_Text = new javax.swing.JTextArea();
        rent = new javax.swing.JButton();
        like = new javax.swing.JButton();
        left = new javax.swing.JPanel();
//        poster = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 32767));

        initComponents(dvdInfo,logonCheck,name,text1);
        //this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String [] dvdInfo,LogonCheck logonCheck,String name,String text1) {

        jPanel1 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        signin1 = new javax.swing.JButton();
        login1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        userName1 = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        director = new javax.swing.JLabel();
        cast = new javax.swing.JLabel();
        name_D = new javax.swing.JLabel();
        name_C = new javax.swing.JLabel();
        introduction = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        intro_Text = new javax.swing.JTextArea();
        rent = new javax.swing.JButton();
        like = new javax.swing.JButton();
        left = new javax.swing.JPanel();
        poster = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 32767));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("在线DVD租赁系统");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));

        background.setBackground(new java.awt.Color(255, 255, 255));

        banner.setBackground(new java.awt.Color(102, 102, 102));
        banner.setPreferredSize(new java.awt.Dimension(186, 60));

        signin1.setBackground(new java.awt.Color(102, 102, 102));
        signin1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        signin1.setForeground(new java.awt.Color(255, 255, 255));
        signin1.setText("注册");
        signin1.setBorder(null);
        signin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        login1.setBackground(new java.awt.Color(102, 102, 102));
        login1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        login1.setForeground(new java.awt.Color(255, 255, 255));
        login1.setText("登录");
        login1.setBorder(null);
        login1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(102, 102, 102));
        back.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("返回");
        back.setBorder(null);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        userName1.setVisible(false);
        userName1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        userName1.setForeground(new java.awt.Color(255, 255, 255));
        userName1.setText("你好，UserName");

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signin1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signin1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName1))
                .addGap(19, 19, 19))
        );

        right.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("微软雅黑", 1, 30)); // NOI18N
        title.setText("影片标题");

        director.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        director.setText("导演：");

        cast.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cast.setText("主演：");

        name_D.setText(dvdInfo[0]);

        name_C.setText(dvdInfo[1]);

        introduction.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        introduction.setText("影片简介：");

        intro_Text.setColumns(20);
        intro_Text.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        intro_Text.setRows(5);
        intro_Text.setText(dvdInfo[2]);
        //intro_Text.setAutoscrolls(false);
        intro_Text.setLineWrap(true);
        intro_Text.setBorder(null);
        jScrollPane1.setViewportView(intro_Text);
        intro_Text.getAccessibleContext().setAccessibleParent(right);
        

        rent.setBackground(new java.awt.Color(255, 102, 0));
        rent.setFont(new java.awt.Font("微软雅黑", 1, 16)); // NOI18N
        rent.setForeground(new java.awt.Color(255, 255, 255));
        rent.setText("立即租赁");
        rent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rent.setPreferredSize(new java.awt.Dimension(80, 25));
         rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
            	if ((!(text1.equals("hi"))) || (!(lo.equals("hi")))) {
					  rentActionPerformed(evt,logonCheck,name);
					  try {
						testReadFile.writeRentFile(name);
					} catch (IOException e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
						
					}
					  System.out.println("success!");
					  try {
							testReadFile.readRentFile();
						} catch (ClassNotFoundException | IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
							System.out.println("read failed");
						}
						 for (int i = 0; i <  testReadFile.arrayListRent.size(); i++) {
							System.out.println(testReadFile.arrayListFav.get(i));
						}
						 
				}
            	else {
					System.out.println("have not login!");
				}
            }
        });

        like.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        like.setText("收藏");
        like.setBorder(null);
        like.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        like.setPreferredSize(new java.awt.Dimension(80, 25));
        like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeActionPerformed(evt,name);
            }
        });

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightLayout.createSequentialGroup()
                        .addGap(0, 213, Short.MAX_VALUE)
                        .addComponent(like, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightLayout.createSequentialGroup()
                        .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(introduction)
                            .addGroup(rightLayout.createSequentialGroup()
                                .addComponent(cast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(rightLayout.createSequentialGroup()
                                .addComponent(director)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name_D, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        rightLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {like, rent});

        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(director, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cast, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(introduction)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(like, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        rightLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {like, rent});

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setPreferredSize(new java.awt.Dimension(230, 335));

        poster.setText("img");
        poster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poster, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poster, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addComponent(banner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        setBounds(275, 125, 841, 513);
    }// </editor-fold>//GEN-END:initComponents
    
    private void rentActionPerformed(java.awt.event.ActionEvent evt,LogonCheck logonCheck,String dvdname) {//GEN-FIRST:event_rentActionPerformed
        // TODO add your handling code here:
    	logonCheck.rentDvd(dvdname);
    }
    /*
    private void rentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentActionPerformed
        // TODO add your handling code here:
        try{
        	//didnot have
            //JDialog_Rent_Success jrs = new JDialog_Rent_Success();  
            lo = HomePage_test2.returnLoginName();
            if ((!(text1.equals("hi"))) || (!(lo.equals("hi")))) {
                rentActionPerformed(evt,logonCheck,name);
                System.out.println("success!");
                //jrs.setVisible(true);
            }
            else {
		System.out.println("have not login!");
            }
          
        }catch(Exception e){
            
        }
    }
    */
    //GEN-LAST:event_rentActionPerformed

    private void likeActionPerformed(java.awt.event.ActionEvent evt,String name) {//GEN-FIRST:event_likeActionPerformed
        // TODO add your handling code here:
        System.out.println("跳转到成功/失败页面");
        try {
			testReadFile.writeFavFile(name);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        System.out.println("success write");
        try {
			testReadFile.readFavFile();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        /*
         try{
          //JDialog_Like_Success jls = new JDialog_Like_Success();  
          //jls.setVisible(true);
        }catch(Exception e){
            
        }
        */
    }//GEN-LAST:event_likeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        HomePage_test2.setLoginPage();
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        try{
          //HomePage_test2 hp = new HomePage_test2();  
          this.setVisible(false);
          //hp.setVisible(true);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_backActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinActionPerformed

    public static void resetBanner(String loginName) {
    	 login1.setVisible(false);
         signin1.setVisible(false);
         userName1.setText("Hello ,"+loginName);
         userName1.setVisible(true);
	}
    /**
     * @param args the command line arguments
     */
    //set the setInfoPage
    //这个方法按照项目要求显示主界面。
    public static void setInfoPage(String name,JLabel jLabel,getPicPath picPath,int width,int height,String [] dvdInfo,LogonCheck logonCheck,String text1) {
    	 lo = HomePage_test2.returnLoginName();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    //windows风格
//                    String lookAndFeel ="com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
                    //metal分隔
//                    String lookAndFeel ="javax.swing.plaf.metal.MetalLookAndFeel";
                    //可跨平台的默认风格
//                    String lookAndFeel =UIManager.getCrossPlatformLookAndFeelClassName();
//                    UIManager.setLookAndFeel(lookAndFeel);
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_Page_new_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_Page_new_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_Page_new_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_Page_new_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //String []dvdInfo = logonCheck.finDvd(name);

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              Info_Page_new_ info_Page_new = new Info_Page_new_(dvdInfo,logonCheck,name,text1);
		      new setPicSize(name, info_Page_new.poster, picPath, width, height);
			  info_Page_new.setVisible(true);
			 
		    	if (!lo.equals("hi")) {
					resetBanner(lo);
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPanel background;
    private javax.swing.JPanel banner;
    private javax.swing.JLabel cast;
    private javax.swing.JLabel director;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextArea intro_Text;
    private javax.swing.JLabel introduction;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel left;
    private javax.swing.JButton like;
    private javax.swing.JButton login;
    private javax.swing.JLabel name_C;
    private javax.swing.JLabel name_D;
    private javax.swing.JLabel poster;
    private javax.swing.JButton rent;
    private javax.swing.JPanel right;
    private javax.swing.JButton signin;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}

